### ISSUE TITLE
Metadata.JSON

### ISSUE THREAD

**Issue by kngautham** [quillford/slack-export-viewer#1]
Hi,

I tried to use your program to convert JSON slack files to TXT files. Your program is asking me to upload a file metadata.JSON.

I am not able to locate this file on slack export data. How do I get this JSON file from Slack?

Thanks

**Comment by adeebshihadeh** [comment]
how did you export your slack data?

**Comment by kngautham** [comment]
I am the Admin and under workplace settings, I used the export option and
downloaded the slack data as a Zip file

[image: MailTag]  Sent with MailTag <https://www.mailtag.io>

**Comment by adeebshihadeh** [comment]
I should have specified this in the readme, but I didn't use slack's export feature because it doesn't include DMs. I updated the readme with the script I designed this around.
